#ifndef RADON_PLATFORM_WINDOWS_H
#define RADON_PLATFORM_WINDOWS_H

#ifdef RADON_PLATFORM_WINDOWS
	#undef RADON_PLATFORM_WINDOWS
	#define RADON_PLATFORM_WINDOWS						1
#endif

// Platform Macros
#define RADON_PLATFORM_DESKTOP						1
#define RADON_PLATFORM_CONSOLE						0
#define RADON_PLATFORM_MOBILE						0

#define RADON_PLATFORM_SUPPORTS_SIMD				1
#define RADON_PLATFORM_SUPPORTS_SSE2				1
#define RADON_PLATFORM_SUPPORTS_NEON				0

#endif